version: '2'

volumes:
  database_data:
    driver: local

services:
  # Nginx Container
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  # PHP Container
  php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./www:/var/www/html

  # MySQL Container
  mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: mysqlpassword
